### PR TITLE
Fix for opacity issue on homepage

### PR DESCRIPTION
**Pull request by calum-bird**
Home page was a bit too opaque. This should fix it.

### CODE REVIEW

**Comment by calum-bird** [comment]
@ScottMktn as discussed

**Comment by chitalian** [comment]
Thanks @calum-bird for your PR. However, I don't think the team is going to accept your PR. We are a company really love our open-source approach and _transparency_ but we don't this is the best way to communicate that with our customers

**Comment by calum-bird** [comment]
Thanks @chitalian, totally understand. It's safe to merge, as my code isn't that good and it turns out this has no effect. Have a nice day sir.

**Comment by calum-bird** [comment]
Okay I was able to fix the bug properly this time. @ScottMktn please approve.

**Pull request closed without merging**
